# Generated by Django 3.2 on 2023-07-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('ruc_dni', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=200)),
                ('obs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('bu', models.CharField(max_length=50)),
                ('validez', models.CharField(max_length=20)),
                ('correo', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=9)),
                ('condicion_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.moneda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente')),
            ],
        ),
    ]
