# Generated by Django 3.2 on 2023-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230720_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha O/P'),
        ),
    ]
