# Generated by Django 3.2 on 2023-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_proforma_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
