# Generated by Django 3.2 on 2023-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_proforma_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='actividad',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='proforma',
            name='observacion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
