# Generated by Django 3.2 on 2023-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.CharField(max_length=200)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
