# Generated by Django 3.2 on 2023-07-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.pieza'),
        ),
    ]
