# Generated by Django 3.2 on 2023-07-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20230726_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cotizacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cotizacion'),
        ),
    ]
