# Generated by Django 3.2 on 2023-07-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_producto_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidad', models.CharField(max_length=20)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='piezasRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='descPiezas/')),
                ('imagen_tienda', models.ImageField(blank=True, null=True, upload_to='imgPiezas/')),
                ('precio_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='descripcioncotizacion',
            name='descripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.piezasrepuesto'),
        ),
    ]
